# Generated by Django 4.0.3 on 2022-03-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_alter_post_options_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.IntegerField(null=True),
        ),
    ]
